import { Container } from '@chakra-ui/react';
import Head from 'next/head';
import Account from '../../components/Account';

const Index = ({ session }) => {
  return (
    <>
      <Container maxW='full'>
        <Head>
          <title>React Playground</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <Account session={session} />
      </Container>
    </>
  );
};

export default Index;
