import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Container, Box, Text, Heading, VStack } from '@chakra-ui/react';
import Hero from '../components/Hero';

const Home: NextPage = () => {
  return (
    <Container maxW='full'>
      <Head>
        <title>React Playground</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <VStack spacing={10} justify='center'>
        <Box>
          <Heading as='h1'> 🙌 Welcome to React Playground !!</Heading>
        </Box>
      </VStack>
    </Container>
  );
};

export default Home;
